// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PawCareApi.Data;

#nullable disable

namespace PawCareApi.Migrations
{
    [DbContext(typeof(PawCareContext))]
    [Migration("20260520172813_AddClinicalEntities")]
    partial class AddClinicalEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PawCareApi.Models.Clinica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Atendimento24h")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATENDIMENTO_24H");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("ESTADO");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("NomeCnpj")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME_CNPJ");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("CLINICA", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long>("IdMedico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MEDICO");

                    b.Property<long>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("IdTutor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("IdClinica");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdTutor");

                    b.ToTable("EVENTO", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.HistoricoClinico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EVENTO");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_VENCIMENTO");

                    b.Property<long>("IdEvento")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO");

                    b.Property<string>("ObservacoesIa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVACOES_IA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento")
                        .IsUnique();

                    b.ToTable("HISTORICO_CLINICO", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.MedicoEspecialista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("MEDICO_ESPECIALISTA", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<double>("Peso")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PESO");

                    b.Property<long>("RacaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RACA_ID");

                    b.Property<string>("StatusLongevidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS_LONGEVIDADE");

                    b.Property<string>("TutorCpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("TUTOR_CPF");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.HasIndex("TutorCpf");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.Raca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("RACA", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.Tratamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_FINAL");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INICIO");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("FREQUENCIA");

                    b.Property<long>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("NomeMedicamento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NOME_MEDICAMENTO");

                    b.HasKey("Id");

                    b.HasIndex("IdPet");

                    b.ToTable("TRATAMENTO", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.Tutor", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("QtdPets")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QTD_PETS");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Cpf");

                    b.ToTable("TUTOR", (string)null);
                });

            modelBuilder.Entity("PawCareApi.Models.Evento", b =>
                {
                    b.HasOne("PawCareApi.Models.Clinica", "Clinica")
                        .WithMany("Eventos")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawCareApi.Models.MedicoEspecialista", "Medico")
                        .WithMany("Eventos")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawCareApi.Models.Pet", "Pet")
                        .WithMany("Eventos")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawCareApi.Models.Tutor", "Tutor")
                        .WithMany("Eventos")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Medico");

                    b.Navigation("Pet");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PawCareApi.Models.HistoricoClinico", b =>
                {
                    b.HasOne("PawCareApi.Models.Evento", "Evento")
                        .WithOne("HistoricoClinico")
                        .HasForeignKey("PawCareApi.Models.HistoricoClinico", "IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("PawCareApi.Models.Pet", b =>
                {
                    b.HasOne("PawCareApi.Models.Raca", "Raca")
                        .WithMany("Pets")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawCareApi.Models.Tutor", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("TutorCpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raca");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PawCareApi.Models.Tratamento", b =>
                {
                    b.HasOne("PawCareApi.Models.Pet", "Pet")
                        .WithMany("Tratamentos")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PawCareApi.Models.Clinica", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("PawCareApi.Models.Evento", b =>
                {
                    b.Navigation("HistoricoClinico");
                });

            modelBuilder.Entity("PawCareApi.Models.MedicoEspecialista", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("PawCareApi.Models.Pet", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Tratamentos");
                });

            modelBuilder.Entity("PawCareApi.Models.Raca", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PawCareApi.Models.Tutor", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
